### ISSUE TITLE
Scanned List (lista scansionati)

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#15]
This is in the menu and should be the list of all scanned product up to that moment.
thankyou

**Comment by rafdelre** [comment]
This is like product list if a single product, and if a box will be a single line with box photo and description

**Comment by hriziya** [comment]
I think, this should be an API call.

**Comment by rafdelre** [comment]
Correct
We are preparing
Thankyou

**Comment by rafdelre** [comment]
Ready as API in json rpc

History.list

thankyou

**Comment by hriziya** [comment]
Can you explain me which property of history.list will give me the highlighted value in this screenshot ?

![image](https://cloud.githubusercontent.com/assets/4135216/7451610/4555d2a8-f270-11e4-913d-2462b63d9414.png)

**Comment by rafdelre** [comment]
Ok We changed this
First off all the layout is very similar to the image (in fact very similar to wish list)
This is what we need:

you will have a result of 
Product row (single scan)
Box row (qr code scan of a box)

so single products will appear
and 1 row per box will appear

now let me explain:
from page 45 of json RPC

created_at is the time and date please write only the time and date no title (localized and timezone be careful)

thats all we need on the title green line (no field or heading on the left)

Now for rows
For a product
When you find a variant, please use usual variant schematic row as in variant list

Now for rows of boxes
For a box use:
icon photo box
first row  >name and store>name
second row

> description

when you list a box please disable the heart. This should be used in the future to select all of the products.

When you click on box please show the box as in box show
when you click on variant please show product detail 
thankyou

**Comment by hriziya** [comment]
Done in 1.0.24

**Comment by rafdelre** [comment]
looks good
