### ISSUE TITLE
Product search result list

### ISSUE THREAD

**Issue by sergiostrampelli** [youppers/app#19]
The result list of product search has the old title and descrption, from the last qr code scan.

If the search is performed before scan, there is the "Description" title, but no description text so if there is no description, why should there be a title?.

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
Maybe the bug was not clear. When searching in list products  (example try 7375) the app returns correctly the list BUT it displays a title that is relative to the box scanned previously

**Comment by hriziya** [comment]
Ohk. Fixed now

**Comment by rafdelre** [comment]
fixed
