### ISSUE TITLE
Product detail page

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#21]
Please remember that the text under attributes (even first line) must be Attributes.value not name

http://demo.youppers.com/qr/5eeed2c7-abb2-11e4-b4aa-0cc47a127a14

Please check always with this box and first 2 rows

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Hitesh the app is now slow when listing products after scan. Why are you item.list for every variant?

You should ask for item.list WITHOUt parameter variant.id.

We have written an example of this in github

**Comment by rafdelre** [comment]
We need the Elementi with the NAMES from the API result

**Comment by hriziya** [comment]
_We need the Elementi with the NAMES from the API result_
Can you share a screenshot for this point ?

**Comment by rafdelre** [comment]
![productdetail01](https://cloud.githubusercontent.com/assets/11840209/7139552/38a8cb7c-e2c7-11e4-8b3c-821d724922de.jpg)

In red is what we need as you can see and has to be changed
So this is what the product detail page should look like.
PLEASE use the color and spacing that YOU use in the app, not red.

You should also take out DECORO. This is an attribute that has variant = FALSE AND there is NO value received with variant read.

use the code in the image to search this product.

**Comment by rafdelre** [comment]
Please remember that the text under attributes (even first line) must be Attributes.value not name

**Comment by hriziya** [comment]
Thanks for the screenshot. It help me understand quickly. 
Done.

**Comment by rafdelre** [comment]
You should also take out DECORO. This is an attribute that has variant = FALSE AND there is NO value received with variant read.!!!!!!!!!!!!!!!

if value is there YOU have to show it!!!!!

**Comment by rafdelre** [comment]
http://demo.youppers.com/qr/5eeed2c7-abb2-11e4-b4aa-0cc47a127a14

click on first product... there are no dimensions... no colors anymore...
that is the most important thing in the app....

**Comment by rafdelre** [comment]
This is an attribute that has variant = FALSE AND there is NO value received with variant read.
So it is a result of this...

in fact it should come out as product 735619.... BUT IT SHOULD ALSO SHOW DECORI...
please ask us if you need help.

So a product detail should have only options that actually have variant == FALSE AND NO values in variant read

**Comment by hriziya** [comment]
This is confusing now..  especially the last comment, Raf. 
Let me do change on how I understand this task.

**Comment by sergiostrampelli** [comment]
So a product detail should have only attribuite types that actually have (variant == True) OR  (Variant==FALSE AND one option of this type in variant read)

**Comment by rafdelre** [comment]
This is better sergio
Thankyou

**Comment by sergiostrampelli** [comment]
See product 726205 as example with a property option of type decoro 

Hope this helps to clarify

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
this looks good
sergio please have a look

**Comment by rafdelre** [comment]
This is working but remember #47
