### ISSUE TITLE
Valid token and stanby

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#22]
Please verify response from rpc using library if you need to ask for a refresh or new token.
This is a serious bug because when the app (tablet) is STANDBY, it will NOT read QR anymore cause no valid token.

**Comment by hriziya** [comment]
Is it possible to refresh token if user is not logged in ?

**Comment by sergiostrampelli** [comment]
No, but can requests a new token with client credentials. If you use a JSONRPC client library, this logic should have been already implemented.

**Comment by hriziya** [comment]
yeah. I already replied this in another task..  
If user is logged in  then refresh_token otherwise get new token.

**Comment by rafdelre** [comment]
Please see #18

**Comment by rafdelre** [comment]
Still problems
if app standbyes 
it does not scan anymore

**Comment by hriziya** [comment]
Added a  fix. Can you try again with new version 1.0.22 ?

**Comment by rafdelre** [comment]
going to test

**Comment by rafdelre** [comment]
Sorry hitesh still no good
I left tablet half a day until now I picked it up... and didnt scan anymore

It seems that the app uses old tokens???

**Comment by hriziya** [comment]
I found one issue when user is logged in.  and app is in Idle for long time..  
In that case, access token is expired and if we try to get new token it will respond with Invalid grant error. 

In that case, we could have two actions.
1) Login user in background.. and we will have refreshed token. 
2) Bring user back to login screen to login again and proceed. 

What do you prefer?

**Comment by sergiostrampelli** [comment]
with refresh token
- send API request with access token
- If access token is invalid, try to update it using refresh token
- if refresh request passes, update the access token and re-send the initial API request
- If refresh request fails, ask user to re-authenticate

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
If app standsby and I was logged
I pickup the app and
IT ASKS FOR PASSWORD????
why?
please debug

with refresh token

send API request with access token
If access token is invalid, try to update it using refresh token
if refresh request passes, update the access token and re-send the initial API request
If refresh request fails, ask user to re-authenticate

thankyou

**Comment by hriziya** [comment]
We are already following same step. I just added one more condition in my logic.  sending you newer version 1.0.30

**Comment by rafdelre** [comment]
it still asks me for authentication
1. start app
2. login through menu
3. scan etc...
4. put device in standby without exiting app
5. restart device
APP ASKS FOR pw
....

**Comment by hriziya** [comment]
It may happen that refresh request failed to get new token.. @sergiostrampelli  Can you please check server side entry and paste it here..

**Comment by rafdelre** [comment]
Hitesh this is a HUGE problem!
Customer cannot use app
We are really loosing time on this
Please
Read the whole post
If we leave standby app IT WILL ASK FOR PW.
Help us please
Thankyou

**Comment by hriziya** [comment]
I already asked for the server side log entry so that I can better see, if any wrong APi called from my side.

**Comment by rafdelre** [comment]
Hitesh my technical staff has already written about this.
We need you to use standard jsonrpc code. So of you have problems send us the piece of code and we will solve it. It is not a server side problem.

**Comment by hriziya** [comment]
You are taking me wrong here.. I didn't say  its server side problem.. I just want to see what response server returned when app wake up from standby. so that I can verify my logic.. 

I am already looking into my code to find and fix it. but getting help from you guys will be necessary for such issues.

**Comment by hriziya** [comment]
You are taking me wrong here.. I didn't say  its server side problem.. I just want to see what response server returned when app wake up from standby. so that I can verify my logic.. 

I am already looking into my code to find and fix it. but getting help from you guys will be necessary for such issues.

**Comment by hriziya** [comment]
I made a fix for it.. sending you new build.

**Comment by rafdelre** [comment]
Thankyou Hitesh

**Comment by rafdelre** [comment]
Thankyou

Sent from my Iphone 5s

**Comment by rafdelre** [comment]
Ok now it doesnt ask for pw when resuming from standby
we are testing
please Hitesh can you test too with the mail I just sent you?
thankyou
raf

**Comment by sergiostrampelli** [comment]
I modified the controller to have more logging and I have finally found the reason.

When the user enter their credentials, with this request the app obtain a token and a refresh token (begins with NT):

```
[2015-05-28 10:05:33] app.INFO: OAUTH Request: grant_type=password&username=sergio&password=************&client_secret=2zxj9pzrsu4gsg4okcswg84c04gwg4g0oko48wog8c0ocoko8o&client_id=4181e57a-cb6c-11e4-b4aa-0cc47a127a14_3jej301vyjy8s0ccwc4w4soo8wc4w4ko0wg00wos8kk4cwgs88 [] []
[2015-05-28 10:05:33] app.INFO: OAUTH Response: {"access_token":"ZDk3MzM4MTJjYzIzOGVjMTQxYzJjMzc0MmY1MzhkZDU2ZGY1NzVjZDNiZjJhZTk2YTMzZjJkZjEzMmY0NjVlOQ","expires_in":3600,"token_type":"bearer","scope":"jsonrpc","refresh_token":"NTg1N2EyYTE4OTU0YzM3ZDVmNzU2MjlhMmRiMDhmOTdhYjIzOGI3NTdmNjEwMjk0NDk5NTA3YWM3NmRkZmU5ZQ"} [] []
```

After a while, the app resume and uses the previous refresh_token (begins with NT) to obtain a new access_token:

```
[2015-05-28 10:06:26] app.INFO: OAUTH Request: grant_type=refresh_token&refresh_token=NTg1N2EyYTE4OTU0YzM3ZDVmNzU2MjlhMmRiMDhmOTdhYjIzOGI3NTdmNjEwMjk0NDk5NTA3YWM3NmRkZmU5ZQ&client_secret=2zxj9pzrsu4gsg4okcswg84c04gwg4g0oko48wog8c0ocoko8o&client_id=4181e57a-cb6c-11e4-b4aa-0cc47a127a14_3jej301vyjy8s0ccwc4w4soo8wc4w4ko0wg00wos8kk4cwgs88 [] []
[2015-05-28 10:06:26] app.INFO: OAUTH Response: {"access_token":"ZjVlMDFkNWVhNGI3MDkyMGRlMjQ5OTZmOTQxYmJkYTkyMGQyMGJmODk0YzVmM2U1Y2Y5ZTFiMTM2ZjliYzA0Nw","expires_in":3600,"token_type":"bearer","scope":"jsonrpc","refresh_token":"MzJmZGMzM2Q4ODdlMTQwOTUyZjNmNTdkYjE0NDFhZmEyOWZiM2I4OGYyMTQ1OGY5M2FkYzFjOWI3Njg5OGRhYg"} [] []
```

But note that **_the server issue also a new refresh token**_ (begins with Mz)

The behavior of the server is correct, as stated in Oauth specifications
https://tools.ietf.org/html/rfc6749#page-48

>   The authorization server MAY issue a new refresh token, in which case
>   the client MUST discard the old refresh token and replace it with the
>   new refresh token.  The authorization server MAY revoke the old
>   refresh token after issuing a new refresh token to the client.  If a
>   new refresh token is issued, the refresh token scope MUST be
>   identical to that of the refresh token included by the client in the
>   request.

But after a while, the app resume and try to use the **old** refresh_token (begins with NT), so the authentication fails:

```
[2015-05-28 10:24:57] app.INFO: OAUTH Request: grant_type=refresh_token&refresh_token=NTg1N2EyYTE4OTU0YzM3ZDVmNzU2MjlhMmRiMDhmOTdhYjIzOGI3NTdmNjEwMjk0NDk5NTA3YWM3NmRkZmU5ZQ&client_secret=2zxj9pzrsu4gsg4okcswg84c04gwg4g0oko48wog8c0ocoko8o&client_id=4181e57a-cb6c-11e4-b4aa-0cc47a127a14_3jej301vyjy8s0ccwc4w4soo8wc4w4ko0wg00wos8kk4cwgs88 [] []
[2015-05-28 10:24:57] app.INFO: OAUTH Response: {"error":"invalid_grant","error_description":"Invalid refresh token"} [] []
```

Also note that the behavior of the app is unpredictable, because **when the refresh_token requests fail** and the user sees the username / password mask **thinking that is disconnected**, the app continues to use the access_token that was issued with the previous request and that this is still valid if not expired (this happens after 1 hour).

PS: This was also with version 1.0.32

**Comment by rafdelre** [comment]
Thankyou sergio
Hitesh please solve
Thankyou

**Comment by hriziya** [comment]
Raf, 1.0.33 worked for this issue  ?

**Comment by rafdelre** [comment]
Thankyou Hitesh
We are testing
Let you know 
Raf

Sent from my Iphone 5s

**Comment by rafdelre** [comment]
Hitesh did you receive my email?

**Comment by hriziya** [comment]
Regarding changing the Menu Icon ?

**Comment by rafdelre** [comment]
Yep
We are testing all other aspects
Thankyou
Raf

Sent from my Iphone 5s

**Comment by rafdelre** [comment]
Hitesh it now works correctly but
If a user is disabled in our backend the app crashes
This is what passes but needs to be attended and needs a correct message:

POST /oauth/v2/token?authendpoint HTTP/1.1
Content-Length: 212
Content-Type: application/x-www-form-urlencoded
Host: demo.youppers.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

grant_type=password&username=lab71&password=lab71&client_secret=2zxj9pzrsu4gsg4okcswg84c04gwg4g0oko48wog8c0ocoko8o&client_idA81e57a-cb6c-11e4-b4aa-0cc47a127a14_3jej301vyjy8s0ccwc4w4soo8wc4w4ko0wg00wos8kk4cwgs88

HTTP/1.1 200 OK
Server: nginx/1.7.9
Date: Wed, 03 Jun 2015 16:43:04 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Cache-Control: no-store, private
Pragma: no-cache
Set-Cookie: PHPSESSID÷q7esjfc7frueqa6ie00n1pu1; path=/
Host-Header: 192fc2e7e50945beb8231a492d6a8024

10c
{"access_token":"YTE0ODNmMDg3ZGZiZDIwZTI0MzMyMTNhNWYwYTk0MGJlMDk2ZWQyNDRkY2I3ZGYzNTUzODc4MjMxMWZjMDA2NQ","expires_in":3600,"token_type":"bearer","scope":"jsonrpc","refresh_token":"MTFjNzBmNjJiOTM3MGMwNDg5OTg3ZWJkYTcxN2MzOThhNTQzNmRhNWI1ZDgyOWUzMThjODdlZDA0NjdhNzA0Mg"}
0

POST /jsonrpc/?access_token=YTE0ODNmMDg3ZGZiZDIwZTI0MzMyMTNhNWYwYTk0MGJlMDk2ZWQyNDRkY2I3ZGYzNTUzODc4MjMxMWZjMDA2NQ HTTP/1.1
content-type: application/x-www-form-urlencoded
Content-Length: 51
Host: demo.youppers.com
Connection: Keep-Alive
User-Agent: Apache-HttpClient/UNAVAILABLE (java 1.4)

{"id":"33","jsonrpc":"2.0","method":"Profile.list"}

HTTP/1.1 401 Unauthorized
Server: nginx/1.7.9
Date: Wed, 03 Jun 2015 16:43:05 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
WWW-Authenticate: Bearer realm="Service", error="access_denied", error_description="User account is disabled."
Cache-Control: no-store, private
Pragma: no-cache
Set-Cookie: PHPSESSID=oc77k2agefijkirmh0iqf68t80; path=/
Host-Header: 192fc2e7e50945beb8231a492d6a8024

49
{"error":"access_denied","error_description":"User account is disabled."}
0
