### ISSUE TITLE
STANDBY

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#23]
We noticed that youppers App on some tablets, never lets the tablet go in STANDBY mode. Please we need the tablet to go in stanby especially if the app is in qr scan and not used. Could you please verify

**Comment by hriziya** [comment]
We haven't added any code that could prevent tablet to go in Standby mode.

**Comment by rafdelre** [comment]
Ok we will test
thankyou

**Comment by rafdelre** [comment]
Our samsung do not go into standby. I am going to verify tonight

**Comment by rafdelre** [comment]
If I exit  app by terminating  and leave the samsung tablet the screen will standby. IF WE have the app opened even in background tablet DOES NOT go into standby.

**Comment by rafdelre** [comment]
If we exit youppers app and STOP the app
The tablet goes in standby

**Comment by rafdelre** [comment]
It looks like the app does now Standby....
going to test...

**Comment by hriziya** [comment]
Do you still have this issue ?

**Comment by rafdelre** [comment]
Yes
Could you test?

**Comment by hriziya** [comment]
What we can do here is..  
we can probably write a code to make it standby when on camera screen.. for that we can read the device setting for standby and command it to go into standby when on Scan page. 

Does that sounds good ?

**Comment by rafdelre** [comment]
Yes but pleae test first

**Comment by rafdelre** [comment]
So now tablet goes in standby if youppers app is NOT IN SCAN MODE

We need it to go in standby also if it is in scan mode...
thankyou

**Comment by hriziya** [comment]
For this issue, we have to decide the time to go in standby when camera scan screen is open. say 5 min or 10 min.

let me know how much should it be ?

**Comment by rafdelre** [comment]
It would be nice to have a menu option settings where to specify

**Comment by rafdelre** [comment]
this and other future settings... for now 10 minutes is ok
