### ISSUE TITLE
Wish Heart on top of list

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#24]
We have decided that the heart on top of list products, shall NOT deselect all
it will only SELECT all as now
thankyou

**Comment by hriziya** [comment]
DONE

**Comment by rafdelre** [comment]
If I click on the heart on top of product list and I dont select anything (no zones), it selects everything anyways... the heart becomes green on all. Please have the app NOT make the hearts green if no zones are selected

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
As said in other issue... lets disable this function.
