### ISSUE TITLE
App crash in menu zones

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#25]
Open app, click on menu, click on list zones, click on one zone and click on X to exit

the app will crash

**Comment by hriziya** [comment]
```
Request:
{"id":"33","jsonrpc":"2.0","method":"Item.create","params":{
    "sessionId":"73c5b059-d09c-11e4-b0ff-0800273000da",
    "items":[{
      "variantId":"6149a4ba-d3aa-11e4-b4aa-0cc47a127a14",
      "zoneId":"b50715bc-c98c-11e4-b4aa-0cc47a127a14"
    },{
      "variantId":"6149a4ba-d3aa-11e4-b4aa-0cc47a127a14",
      "zoneId":"c6f6f8e4-c98c-11e4-b4aa-0cc47a127a14"
    }]
  }
}

```

After login, when we don't have the variant ID..  in that case, what should we pass for Item.create method ?

**Comment by rafdelre** [comment]
Ok app doesn't crash anymore.
BUT you should not be able to choose a zone from menu list zones cause it has no sense. You should only be able to list the zones or add a zone (then you have login)
The zone choice should only be active when in a product (heart)

**Comment by hriziya** [comment]
Done..

**Comment by rafdelre** [comment]
Ok it does work BUT
If I choose to add a zone (create zone) from menu choice, I create it and then it correctly asks me to login... then I login... but I dont see the new zone???
going to test... please sergio you too

**Comment by hriziya** [comment]
Fixed
