### ISSUE TITLE
Images in product details

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#26]
If in details there is an image instead of a pdf it will not open

Please open the 2nd item in box bagno1 (the link we gave you)

so you need to specify CONTENT TYPE

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
I meant that we needed to open pdfs and images....

now it opens only images and pdfs will trigger image type!!!!!!!!!!!

please we need this corrected

CONTENT_TYPE

**Comment by rafdelre** [comment]
We Have tested again. it is actually working.
Please can you test also?

It seems like it is working.
It looks like the problem could be pdf app reader related, NOT youppers app. 
Thankyou

**Comment by hriziya** [comment]
yeah. working for me too.  you can try removing all stored data of youppers app from "PDF" folder in your file manager.
