### ISSUE TITLE
Product detail variant

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#27]
When in a product detail, when selecting a measurement for example, or any other attribute, the app should show the new variant product if present from API data (so it should change image and data)

**Comment by hriziya** [comment]
Can you explain more or a screenshot ?

**Comment by rafdelre** [comment]
You are doing everything, but let explain:

http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

qrcodescan BAGNO1

then click on first product (tonic bidet)

Click on First dimension (36x40x54)

Then click on 36x39x55 

Then click on 36x39x54   THIS IS CORRECT because it shows the list of product variants.

The first 2 ARE actual products with no list. This is correct BUT
(36x40x54)  this one should UPDATE THE PAGE and show K310101
(36x39x55) this one   should UPDATE THE PAGE and show K313261

If this is not clear please tell us
thankyou

**Comment by hriziya** [comment]
This is done

**Comment by rafdelre** [comment]
sergio could check? it looks good
