### ISSUE TITLE
Product detail elementi

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#28]
When clicking on any Elementi, if more than ONE variant is found, it should  present a list page products as the one after qr code scan as WRITTEN in WORKFLOW page 8.
If it is unclear please let us know.
This should allow customer to have more products of the same kind for the selected one

**Comment by hriziya** [comment]
Request:
`{"id":"33","jsonrpc":"2.0","method":"Variant.list","params":{"collectionId":"af733bdf-d24a-11e4-b4aa-0cc47a127a14","sessionId":"f6349652-e2a2-11e4-b4aa-0cc47a127a14","options":["43936ab2-b604-11e4-a918-0800273000da"]}}`

If more than one variant is found.. then 
say, if there is NO variant ID in response.. 
should I use the variant ID that was used to get the collection ID ?
or I have to keep the attribute of list disabled ?

**Comment by hriziya** [comment]
I have displayed the list for now

**Comment by rafdelre** [comment]
Yes it lists correctly!. but we have "non disponibile"

You said " if there is NO variant ID in response.. "

Let me answer:

variant ID is simply id of the response because the response is an array of variants

Page 27 of RPC doc
thankyou

**Comment by hriziya** [comment]
This is done.
