### ISSUE TITLE
search in product list

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#29]
search works, but in list itt should be same as product list when result of a scan
please test.
use 7375

**Comment by rafdelre** [comment]
If I search I cant go back to box list?????
why???
these should be different ACTIVITIES
this is FUNDAMENTAL
PLEASE!

**Comment by hriziya** [comment]
I did not get you..  please share screenshot of what you are experiencing ? 
I scan a qr code.. and the result listed.. then I tried searching "7375" and it does display the list..  I pressed back button, and I can see the previous list as is..  

Is this what you are following ?

**Comment by rafdelre** [comment]
It is working
thankyou
