### ISSUE TITLE
Wish List Zones

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#3]
if we add a list item to wish list to 3 zones for example and close zone list, then click again on same item, we get the 3 zones. Then we click on a selected zone to delete it and we remain with 2 zones. CORRECT. BUT IF WE open that item again, we get 3 zones (the original ones) and after 1 second we get the correct 2 zones. PLEASE request from server BEFOR listing zones.

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Thankyou
