### ISSUE TITLE
Keyboard login

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#30]
is it possible to have keyboard popup right away when clicking on login? it now doesnt appear as soon as in the field username. You have to click on the field to have it popup
thankyou

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
It works from the menu, BUT NOT from End session and send via email........
plus why does it ask confirmation BEFORE it logs in in end session with email?
If user is logged in and user "Ricevi la lista dei preferiti via e-mail": thats when it should ask confirmation

If user is not logged in, then it should right away propose the login page
then it should ask confirmation
and if user ansers confirm, it should exit and send email

thankyou

**Comment by hriziya** [comment]
Fixed
