### ISSUE TITLE
Product list after scan

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#33]
Version 1.0.7

scan Bagno1

http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

go to bottom of list you  will see 2 products, one has only Y and name: correct
The last has logo Ideal standard and all infos 

These are particular cases described in RPC document.

NOW switch to APP 1.0.8

you will see that the LAST item after scan of Bagno1.... IS EMPTY

we didnt change anything.

Please debug

**Comment by rafdelre** [comment]
and if you click on the last row or the one before, of product list... app crashes

probably NO variant.id

**Comment by hriziya** [comment]
Fixed
