### ISSUE TITLE
Product list add to zone

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#34]
Scan a box
http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

click on first item Heart

zone list appears

click on first zone

THEN click on BACK in top of app <

The menu is NOT MODAL. ANY window (menu) that has a X or a button to exit SHOULD BE MODAL.

and the "hard button" return of android should reflect this.

**Comment by hriziya** [comment]
Done.

**Comment by rafdelre** [comment]
Almost
I can still click in the middle part of the screen

rest is ok

**Comment by hriziya** [comment]
middle part of which screen ? 
Are you on zone list or menu ? screenshot would help more

**Comment by rafdelre** [comment]
Hitesh. Open the zone list by clicking on a heart in one product

Then click out of the menu (left side) where you can see shaded the product detail
It interacts...and should not. It is not modal....
is it clearer ?
please tell me if you need more...

**Comment by hriziya** [comment]
This is clear now.. Than you.. will fix it..

**Comment by hriziya** [comment]
Fixed
