### ISSUE TITLE
Product Detail from variant list 

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#38]
Bagno1
http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

click on 3d element (A5708AA)

click on 2nd variant in horiz list
Rub. Lavabo

you have the list of variants. This is perfect

NOW click on one of them to have the product detail....

First time it wont show

Second time it will...

thankyou

**Comment by hriziya** [comment]
Fixed it now

**Comment by rafdelre** [comment]
fixed
