### ISSUE TITLE
Box photograph 

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#39]
This should be positioned on the fixed line where box description is. It should be  an icon, and if clicked it should fill screen, 
if it is not present in api, then no icon

**Comment by rafdelre** [comment]
#40

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
I dont see it
Where do I find this?
I would expect when qrscanning a box I find it in the top part where Description is?
thankyou

**Comment by hriziya** [comment]
Can you give me sample product number to look for ?

**Comment by rafdelre** [comment]
Hitesh this should be on top of the list of a box where description is

Bagno1

This is the same photo that we put in product detail of the single product
Its just the photo of the box
If you need example tell me

**Comment by hriziya** [comment]
Yes. please give me example. that would be better to understand

**Comment by rafdelre** [comment]
![screenshot_boxphoto](https://cloud.githubusercontent.com/assets/11840209/7363933/caa7c230-ed80-11e4-98ed-998aeb16f2f3.png)

should go also:

![screenshot_boxphoto2](https://cloud.githubusercontent.com/assets/11840209/7363936/d369508c-ed80-11e4-9159-ed0e0e434266.png)

and if clicked go full screen to see it

thankyou

**Comment by hriziya** [comment]
Done
