### ISSUE TITLE
Box description and photo in product detail

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#40]
this should be listed right after docs.
this is the same as description and icon image box in BOX list

if image is clicked it opens image full screen

If description is clicked it should do similar to   qrcode scan of box.
This has a dedicated API

Obviously the BOX description will be present only if there is a Store in Session.

The field in API result for youppers_dealer_box is "image"

**Comment by hriziya** [comment]
Need more explanation.. 

Are you talking about the DOCS section at bottom of product details page ?

**Comment by rafdelre** [comment]
Yes
It should just be a line under docs section at the end of everything
It will be there only if product is in a store and if app is in a valod store

Please this is an addom. Everything in product detail should remain 
Thankyou

**Comment by hriziya** [comment]
![image](https://cloud.githubusercontent.com/assets/4135216/7174620/77a997fe-e428-11e4-8fc7-308de715f42a.png)

Here we have Image on right.. so clicking on Image will zoom it to full screen. and clicking on text will call an API ?

**Comment by rafdelre** [comment]
Exactly
So that when we have description of 'parent box' and image exactly like the last row
YES we click on description and it opens box so yes a new API

**Comment by hriziya** [comment]
Ok..  which API would it be ? and Is it added to Youppers google doc ?

**Comment by rafdelre** [comment]
Sergio is adding it now
If you want we can test fixed product detail hitesh?
I mean the one thst yerstaday wasnt showing any atteibutes?

**Comment by hriziya** [comment]
Ohk.. I will wait on it..  we are working on that #21 
so, it will be done in next few mins, then I will send you new APK.

**Comment by rafdelre** [comment]
Great

**Comment by sergiostrampelli** [comment]
The JSONRPC document is now updated with the new functions related to boxes. 
Bye
Sergio

**Comment by hriziya** [comment]
I read the document, but still not clear on when should I call  Find Box, Show Box and Search Box ?

**Comment by rafdelre** [comment]
Sergio lets explain this

**Comment by sergiostrampelli** [comment]
The API **_Box.list**_ should be called after Variant.read / Collection.read / Attributes.read to display the section "Allestimenti" (Settings) in product detail page.

![image](https://cloud.githubusercontent.com/assets/9050752/7186501/8706ad4e-e46a-11e4-8323-c2f30e8b15eb.png)

The small image (right side) is **_image > url**_
When the user clicks on the image, you show **_image > url.reference**_

On the left:
1st row: **_name**_ field, in the example "Bagno 1"
2nd row: **_description**_ field (could be multiline), in the example "Ideal Standard Tonic,Neon,Ultraflat,Kubo,idealrain,strada"

if more boxes, do it as for DOCS section.

When the user clicks on text, the app uses **_Box.show**_ to show the box page, that looks like the page that the user sees when scans a QR.

**Comment by rafdelre** [comment]
Could you please change "Settings" to "Location"
thankyou
raf

**Comment by hriziya** [comment]
Done
