### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#41]
we need to know if user is logged in. That is, if a user is correctly logged in, then accedi (login) should be logoout (disconnetti) in menu,

**Comment by hriziya** [comment]
when text is Logout, do we need any API call there?

**Comment by sergiostrampelli** [comment]
No.
When Logout is clcked, the App discard the current token with grant password and obtain a token with grant client

**Comment by hriziya** [comment]
so I would ended up calling api to get new access token ?

**Comment by rafdelre** [comment]
If a session has items, before you can logout user has to end session, else he is free to logout

**Comment by hriziya** [comment]
If user do not end session then ? should we prevent from logout ?

**Comment by rafdelre** [comment]
Sergio?

**Comment by rafdelre** [comment]
We need user to be able to logout...

Sent from my Iphone 5s

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Sergio could you test if actually disconnected
thankyou
raf

**Comment by rafdelre** [comment]
I tried logging in
I created a new zone in wish list
then i tried to log out
it showed I was logged out
BUT it stil gives me the same list as when I am logged in

something is wrong
thankyou

**Comment by hriziya** [comment]
When session has items, we will bring use to end session screen so they can choose either of those three end session option and afterword proceed with logout.. 

If current session does not contains any items, then should I end session ?

**Comment by rafdelre** [comment]
Well if it contains scanned items, it should end session

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Sergio please test

**Comment by rafdelre** [comment]
If a user is logged and has a session, when you log out, you have to end session!

**Comment by hriziya** [comment]
Do you mean, you want to end session directly instead of showing "End session" screen to user ?

**Comment by rafdelre** [comment]
No hitesh
Let me discuss this with my associates
Thankyou

**Comment by hriziya** [comment]
Let me know if you need any change. refer latest version 1.0.26
