### ISSUE TITLE
Product list

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#42]
or scan result

Please, we need a standardization for click event to enter product detail.
1. we need to be able to click on center part (text) of list and immediately show product detail. Now there is a bug where only a portion and only image goes into product detail.
2. Please have the picture expand into whole page instead of entering detail (same as in product detail)

Please tell us if unclear
this is VERY important
thankyou

**Comment by hriziya** [comment]
Done. clicking on thumb will enlarge that image and clicking on row text will direct you to details page

**Comment by rafdelre** [comment]
working
