### ISSUE TITLE
HEART DOES NOT WORK ANYMORE

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#44]
we are going backwords HITESH

I cant test everything everytime
PLEASE
 If I select a zone after pressing heart it doesnt become green anymore

I repeat this is frustrating because it used to work!!!!

**Comment by rafdelre** [comment]
looks like its working... 1.0.10
testing

**Comment by rafdelre** [comment]
NO NOT WORKING

I cannot replicate when... but server side is ok... the problem is a refresh when in scanned list... in fact if I scroll list and go back it qill become green

PLEASE VERY URGENT

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
click on a products heart and select a zone
heart becomes green
click again on the heart and click on the zone to delete it
X
and back to list....
heart still green!!!!!!!!!!!!!!!!!!!

HELP!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hriziya** [comment]
Fixed
