### ISSUE TITLE
Help doc in menu

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#45]
Please remember to include a choice in menu before Info:
Help

It will be a link to a pdf

thankyou

**Comment by hriziya** [comment]
Can you add the URL for PDF ?

**Comment by rafdelre** [comment]
Hitesh this should be in language files
help_str and help_url

**Comment by hriziya** [comment]
OK. you can add it to XML when you update text and so later I can put updated file in app. I will link Help menu with help_url PDF file

**Comment by rafdelre** [comment]
Great
One more thing
There should not be color or size in the files. These are not titles in the app. 
Thankyou

**Comment by hriziya** [comment]
It was in use previously.  Not in use currently.

**Comment by rafdelre** [comment]
Ok
Thankyou

**Comment by hriziya** [comment]
If you have "help_url" value then give me url otherwise I will use any dummy url for now

**Comment by rafdelre** [comment]
http://www.youppers.com/help?locale=it

**Comment by hriziya** [comment]
you said it will be a link to pdf ?

will it be a web page that I can open in browser ?

**Comment by hriziya** [comment]
Let me know if you need any change in this.. I opened Url into browser for now.

**Comment by rafdelre** [comment]
sergio is this ok?
