### ISSUE TITLE
Product Detail Variant and options selection

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#47]
Scan Bagno2

Select Rivestimento doccia (8th row)

Product detail

Everything is correctly selected

NOW select Dimension 15x60 cm

App shows list of ALL 15x60 forgetting the fact that We had also selected MATTE and VAR

Please this is FUNDAMENTAL

**Comment by rafdelre** [comment]
Scan Bagno1
click detail for first row Bidet
it shows 36x39x54
click on heart and put it in Bagno1 as wish list
heart becomes green correctly

Now select a variant 36x40x54

heart stays green?

then I go back to first and heart is not green?

need fixing please

**Comment by hriziya** [comment]
Fixed
