### ISSUE TITLE
Product List after scan box WHITHOUT a Variant

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#48]
please scan the 3d qr code

http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

(Pannelli Scorrevoli)

If you look at the centre part description

You have 

nome   serie    brand
1          736144 rex

THIS SHOULD BE

nome   codice  brand    

this is WRONG only for the first 4 (non disponibile)

While for the others it is correct!!!

Please be careful Hitesh!!!

Please

the others are CORRECT.

**Comment by hriziya** [comment]
Fixed
