### ISSUE TITLE
IMPORTANT: new session after login

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#5]
THIS IS VERY IMPORTANT: when loging in the app  requests a new session. NEVER ASK FOR A NEW SESSION WHEN LOGIN. IT LOOSES all data from the previous session. PLEASE refer to workflow. The app has to tie session with login

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Sergio please verify
thankyou

**Comment by sergiostrampelli** [comment]
The App don't start a new session just after login: the new session is started when a qrcode is scanned.

**Comment by rafdelre** [comment]
This is on page 4 WORKFLOW doc
The app should NEVER Session.new
only when terminated session (end session) . This is the only time the app should discard session.

New session is when you terminate
or when you dont have it because the app was just started

when you login, you should Session.read
The server will associate with session.

**Comment by hriziya** [comment]
For now, I am calling http://demo.youppers.com/oauth/v2/token?authendpoint for login.. 
as  you've suggested, Today, I will call Session.read after login.

**Comment by sergiostrampelli** [comment]
IMHO sessionId should persist also in case of crash of the app

---

Ing. Sergio Strampelli
Ufficio (+39) 06 90285655
Cell (+39) 340 3480044

Il giorno 09/apr/2015, alle ore 06:45, Hitesh Riziya <
notifications@github.com> ha scritto:

For now, I am calling http://demo.youppers.com/oauth/v2/token?authendpoint
for login..
as you've suggested, Today, I will call Session.read after login.

**Comment by hriziya** [comment]
I am not sure on how would I get the Application crash event..   because we can handle the app start /  logout event for creating new session.  but if you put app in background and then quite it. in that case we don't have any event to keep the session ID.

**Comment by sergiostrampelli** [comment]
I think the best solution if to store sessionid in a table of a local database:

http://developer.android.com/guide/topics/data/data-storage.html#db

**Comment by rafdelre** [comment]
Please remember that Session is important even if not logged in. It means that we need to keep sessions to bind to users or to find activity in that session EVEN if no user registration.

Imagine you enter in a SHOWROOM where the youppers app is running and we need a tablet to go around scanning qr codes EVEN without a login. ANONYMOUS. This could also be for hours.... SO ONLY when  END SESSION or END WITH CONSULTANT you should release that session. 

We need to to keep this consistent

**Comment by hriziya** [comment]
Done. now session will only end on "End session" or "End with consultant" option.

**Comment by rafdelre** [comment]
This looks good Hitesh
Sergio can you verify please?
