### ISSUE TITLE
Product Detail Selected Choice

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#50]
It is now better with the new dimension around select choice...
BUT we really need to make that color RED (same color as the red in Y of youppers logo)
This is really important because users cannot see the choice
thankyou
#46

**Comment by rafdelre** [comment]
Please test with code

737678

it still needs work. It is slow and chunky. 

the red is good... BUT we nedd uniformity thtroughout the rows

What I mean is that the graphics in ,color, dimension ARE NOT THE SAME. We need that the squares be same height and width (80)

please also have a TIMEOUT when selecting choices in detail . If server does not answer in 5secs please timeout

**Comment by hriziya** [comment]
Done.

**Comment by rafdelre** [comment]
Let us all test this please

**Comment by rafdelre** [comment]
there are problems with icon size elementi

**Comment by hriziya** [comment]
Any open issue for this task ?

**Comment by rafdelre** [comment]
Closing
Thankyou
