### ISSUE TITLE
change request in Attributes.read parameter

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#52]
in json rpc in your drive you have a new parameter to add when Attributes.read   : variantId

currently you are passing collectionId with the value

We need you to pass instead, variantId with relative value

This should list a much better and cleaner attributes... also smaller

the format is exactly the same and you should NOT change ANYTHING else please

**Comment by hriziya** [comment]
This is also done but I haven't included it in 1.0.14.. because response needs to be changed from Object to Array.

**Comment by sergiostrampelli** [comment]
I have just fixed the server code: now returns the attributes as array.

**Comment by rafdelre** [comment]
Sergio can I close this?
