### ISSUE TITLE
End session sendin email

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#53]
When clicking on "concludi sessione" AND 
"ricevi lista dei preferiti via e-mail" (end session and send me email

the app does not correctly end the session

Try selecting a box by scanning bagno1

add to favourite (with heart) first product

then clicki on "concludi sessione" AND 
"ricevi lista dei preferiti via e-mail" (end session and send me email.

put user 

raf
pw nomos

all seems correct... but

if I scan again bagno1...
I get the old favourites...

not a new session... not logged out?

**Comment by rafdelre** [comment]
#51

**Comment by hriziya** [comment]
Fixed
