### ISSUE TITLE
Graphics in detail is wrong

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#54]
try searching
E713101

the graphic icons in Elementi are wrong Hitesh

the border red is fine!

the square line around not select should be one line and that is ok

On newer tablets the scrolling looks good.

Lets test

but please have the graphics in Elementi come back to right size
thankyou
raf

**Comment by hriziya** [comment]
FIxed

**Comment by rafdelre** [comment]
it is fixed but focus in dimensions with code e713101 is not correct.
before it was working.
could you test?

**Comment by rafdelre** [comment]
VERY URGENT!

**Comment by hriziya** [comment]
Can you tell me how does it sounds incorrect to you ? 

It does select the 55x45 in dimension and scroll bring it to visible area on device..   what is incorrect ?

**Comment by rafdelre** [comment]
Hitesh I see it selected but it is not in focus. It used to be.
Sergio can you confirm please?

Sent from my Iphone 5s

**Comment by rafdelre** [comment]
![asus prima screenshot_2015-04-23-13-10-19](https://cloud.githubusercontent.com/assets/11840209/7298463/0b265b1e-e9d0-11e4-86be-b935d9bbf3d2.jpg)
![asus dopo screenshot_2015-04-23-13-10-42](https://cloud.githubusercontent.com/assets/11840209/7298464/0b2ac0fa-e9d0-11e4-8168-f3199c4c2758.jpg)
![samsung prima screenshot_2015-04-23-13-10-46](https://cloud.githubusercontent.com/assets/11840209/7298465/0b2d3a6a-e9d0-11e4-8fff-9d6cfebaa041.png)
![samsung dopo screenshot_2015-04-23-13-12-54](https://cloud.githubusercontent.com/assets/11840209/7298466/0b2da658-e9d0-11e4-98a9-525299be8614.png)

These are 2 examples that are happening hitesh

Please confirm you see the bug

thankyou

**Comment by hriziya** [comment]
Yes, I can see it now.  In progress..

**Comment by hriziya** [comment]
Done
