### ISSUE TITLE
Variant not listed in product detail

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#56]
If a variant returns an attribute that is not listed in product_attributes of Collection.read, it must be shown without the selector (only name in green 1st row + value in gray 2nd row)

**Comment by hriziya** [comment]
_it must be shown without the selector (only name in green 1st row + value in gray 2nd row)_

Please explain this.

**Comment by rafdelre** [comment]
Ok Hitesh let me try
If a variant returns an attribute that is not listed in product_attributes of Collection.read, it must be shown without the selector (only name in green 1st row + value in gray 2nd row)

this is an extract from last page in JSON RPC in google drive

from page 27 on

It means that in the app we are not seeing single variants that just supposed to be listed not chosen
I am going to explain better with an example
they are proprieties of a variant but are not product attributes.
So not selectors
they have to be added as a list.

Please read that part again in google docs

this is fundamental
thankyou

**Comment by rafdelre** [comment]
try bagno1 (box)

on the list it has all the products 

you will notice that the first product has some specific attributes

![misc](https://cloud.githubusercontent.com/assets/11840209/7280091/d55eb27e-e920-11e4-8271-9d49e2c13a50.png)

but they should be shown as in JSON DOC
thankyou

please leave everything else as is
working

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Good
