### ISSUE TITLE
WISH LIST ....VERY URGENT!!!!!

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#60]
click on a product
in product detail
add to wish list with heart
select a zone (first one)
then click X
and the heart becomes correctly green

then select heart
and deselect zone (first one)
click on X
heart becomes white

CORRECT
NOW

try clicking again on heart and selecting a zone
it will become correctly green

HERE IS THE BUG

Click on the heart:

NO ZONE

you do not pass variantid anymore

**Comment by hriziya** [comment]
Fixed
