### ISSUE TITLE
End session with consultant

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#63]
Concludi sessione con consulente

The button on the bottom to end session in center bottom says
Concludi Sessione

It should say Conferma

Thankyou
raf

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
But it says Confirmation

I need CONFERMA

thankyou

plus if I dont select any consultant.... it should NOT let me confirm with button (the button should be disabled but present)
thankyou

**Comment by hriziya** [comment]
Fixed
