### ISSUE TITLE
Add to wish list Heart bug VERY URGENT

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#67]
Scan Bagno1

go to first product detail

click heart

select a zone

and close

App correctly adds to wish list  and heart becomes green

now click on a different measurement to have the detail change product

now try clicking on heart

NOTHING HAPPENS

(maybe variantId not passing)
thankyou

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
scan box1 (bagno1)
click on first heart
select bagno1 and bagno2 zones
click on X

no w go to lista preferiti (wish list)

you have correctly the product shown twice one in bagno1 and one in bagno2

click on green heart first selection and remove zone bagno2

see what happens!

should make the second row white....

thankyou

**Comment by hriziya** [comment]
Fixed in 1.0.24

**Comment by rafdelre** [comment]
Hitesh its all wrong. Im sorry but this is a mess!

**Comment by rafdelre** [comment]
Try it yourself.
Scan box1 bagno1

click on first product heart
add it to bagno1 zone
click X
heart green
perfect

now click on green
why does it ask to delete it right away?
I mean to delete it I should first be presented with the list and if I want to delete it I just remove all the zones. This was so before.

Now if you say yes I want to delete the heart remains white
correct BUT if I click it again I have the zones still selected????

PLEASE DEBUG if you need help ask

we really have problems with this not working
raf

**Comment by hriziya** [comment]
Fixed in 1.0.25

**Comment by rafdelre** [comment]
looks good
