### ISSUE TITLE
User login when creating a new zone

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#68]
There is an error:
Please enter inserisci la tua e-mail (this is in italian or english) this happens if you dont enter a email
The text is half english half italian

AND MOST IMPORTANT 
If I add a new zone and the zone is ALREADY there
and the app asks for login

It just keeps on asking for login...
It should say Cannot add ZONE

So Lets change order
1. when pressing add new zone, first if user is not logged, ask for login
2. then ask for new zone if user has logged correctly
3. if user already logged, just ask new zone, if zone already present, it should say zone present

thankyou

**Comment by rafdelre** [comment]
I tried changing user
It messed up completely

so please
you can log with
raf
nomos

or
abc
abc

please test this

thankyou

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
much better
