### ISSUE TITLE
VERY IMPORTANT: standby and qrcode scan

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#7]
If we are in the app and we standby the tablet, we pick up the tablet and enter app, it will not scan qr codes anymore… have to exit app and reenter

**Comment by rafdelre** [comment]
The server probably is giving back an error (token expired maybe ?) please verify and handle the errors (please show the error)

**Comment by hriziya** [comment]
I found one token related problem in code when in standby. just fixed it.

**Comment by rafdelre** [comment]
Thankyou
The problem now is that if I abandon the app, and restart it it doesnt pick up from where it was.... it starts all over.
We need this:
1. if we are in the app and it goes into standby, when picked up again it should scan correctly and stay where it was. This is working
2. if we manage to exit app (in background) and re-enter, app will start from beginning forgetting everything... this is wrong
thankyou

**Comment by hriziya** [comment]
if we manage to exit app (in background) and re-enter
// Have you quit the app once it is moved to background ? or you just push app to background and it lost data ?

also, on which device you checked this case ?

**Comment by rafdelre** [comment]
no. that's the problem. I havent quit the app. if I enter again, it will start from scratch

**Comment by hriziya** [comment]
Ok. I made a small fix for it..  

now, if we put app in background and then re-enter into the app will show you your running session.

**Comment by rafdelre** [comment]
Ok it does work now.
