### ISSUE TITLE
User registration and profiles

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#70]
We have decided to use only profiles and no user registration in the app
so we need this api in the app please:

Profile CRUD 

in JSON RPC

you can find explanation in workflow

if you need help please ask us

thankyou

**Comment by hriziya** [comment]
I did not found any screen for Profile CRUD operation. 

Please provide screen layout as this wasn't the part of original requirement document.

**Comment by rafdelre** [comment]
Ok
We are working on helping you
Thankyou

**Comment by rafdelre** [comment]
Hitesh this is what we need
We dont need any new graphics:

Workflow page 4.
Activity Profile Select
Lets make this exactly like zone list select BUT REMEMBER ONLY ONE SELECTION IS POSSIBLE. This is exactly like Heart click. This has to be done right after correct login.

Workflow page 5.
Profile list
Lets make this exactly like zone list BUT NO SELECTION (see edit and delete). 
This should be a new menu choice called Profile List.
This should be exactly like zone list when called from menu.

Workflow page 5.
Profile Edit (NEW)
Lets make this exactly like zone list when you press + (add new zone).

Workflow page 5.
Profile Edit
This should be click of one profile FROM MENU Profile List. This will popup same edit box as NEW but with an added button delete. 

Workflow page 5.
Profile Delete
Lets make this a confirmation of the above delete.

**Comment by hriziya** [comment]
OK. I got it. 

one question..  
when user click the row from profile list popup menu ..  
should I consider that click as selection or for edit ?

Another thing is, for default profile we may have name blank.. in that case what is the way to edit that profile info ?

**Comment by rafdelre** [comment]
If its profile list from menu will be edit and delete as above described
The blank default can be edited
Thankyou

**Comment by hriziya** [comment]
Ok got it

**Comment by hriziya** [comment]
Done in 1.0.24

**Comment by rafdelre** [comment]
Hitesh I thought we said that  after login... profile list is suppose to list?

**Comment by rafdelre** [comment]
ok if there is no profile or just default this is correct

we are going to test more
thankyou

**Comment by hriziya** [comment]
In progress yet.

**Comment by hriziya** [comment]
Error when try to delete profile.

```
{
  "id": "33",
  "error": {
    "data": "An exception occurred while executing 'DELETE FROM youppers_customer__profile WHERE id = ?' with params [\"66e8d8e9-dcb6-11e4-b4aa-0cc47a127a14\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`youppers_demo`.`youppers_customer__zone`, CONSTRAINT `FK_1ED8DB5FCCFA12B8` FOREIGN KEY (`profile_id`) REFERENCES `youppers_customer__profile` (`id`))",
    "message": "Internal error",
    "code": -32603
  },
  "jsonrpc": "2.0"
}
```

**Comment by rafdelre** [comment]
Yes it is correct
The zone is associated and is in use
Cannot be deleted

**Comment by hriziya** [comment]
In such case, what should I display in app ? 

I think, you should return some user readable message from web api which I can display in popup box to user.

**Comment by hriziya** [comment]
also, I can only delete newly added profiles which I recently added after login, but can not delete old profiles which were added in prev login.

**Comment by hriziya** [comment]
1. Please make the button Profili (profiles) Not selectable. It throws confusion to end user. So also please just leave the user in default profile. When user logs in please dont ask profiles anymore. Just use default one. Leave the code we will use it in the future.

// DONE
