### ISSUE TITLE
Product image and media in list and detail

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#72]
The image loaded in the list of products and detail is correctly loaded ONLY  IF an image is found in the result api.

WE NEED YOU TO load an image always

How do you do this:
1. check if an url for product image 
   if IMAGE 
   display

if NO IMAGE 
please check if COLLECTION has an image
if IMAGE 
display

if NO IMAGE
please check if brand has an image
if IMAGE
display

if NO IMAGE
please check if company has an image
if IMAGE
display

if NO IMAGE

PLEASE display YOUPPERS LOGO

Thankyou

**Comment by hriziya** [comment]
Done in 1.0.25

**Comment by rafdelre** [comment]
this does not work
please search:
EPOQUE

we have taken out variant image and put ONLY COMPANY IMAGE
it is not showing

please verify today and send an apk if possible
thankyou

**Comment by rafdelre** [comment]
Hitesh this is not working and is The most important BUG to fix:
try searching:
B9120

It shows the brand logo

BUT if you scan this box:
http://demo.youppers.com/admin/youppers/dealer/box/7dafaf26-051a-11e5-b4aa-0cc47a127a14/show

you will see that the list has Y and NO brand logo?
also on the detail no logo (brand)

please have this fixed
please debug
