### ISSUE TITLE
Qr code scan from photo album

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#79]
Hitesh is it possible to enable scanning from a qr code photo saved in local album?

**Comment by hriziya** [comment]
Well, I guess its not doable.

**Comment by rafdelre** [comment]
Well any qrcode app (qrcodescanner) can scan from gallery. Could we with a small button?

**Comment by rafdelre** [comment]
Qrcodereader app  has the function.

**Comment by hriziya** [comment]
Done
