### ISSUE TITLE
menu icon

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#81]
Hitesh But the menu icon is on the writing
the file schema copy does not look like what we have now
Did you open the app and scan a box?
please.......

**Comment by rafdelre** [comment]
![screenshot_2015-05-29-11-31-41](https://cloud.githubusercontent.com/assets/11840209/7962614/97da8a7c-0a0e-11e5-9e83-542b323556b5.jpg)

**Comment by rafdelre** [comment]
![15 05 28_schema copy](https://cloud.githubusercontent.com/assets/11840209/7962637/b6704620-0a0e-11e5-8399-392ac8364eca.jpg)

**Comment by rafdelre** [comment]
Please the Menu icon is now TOO BIG

please make it the same as in the above pictures

thankyou

**Comment by hriziya** [comment]
Regarding point 4.  currently we are adding shadow programatically. 
can you please send me the Favorite, Scan, End session images with drop shadow..  ?

**Comment by sergiostrampelli** [comment]
I assumed that the shadow is a feature off-the-shelf" (like OAuth2 and JSON-RPC), not a work for graphics peoples:

https://developer.android.com/training/material/shadows-clipping.html

May be that you are doing the wrong way?

**Comment by rafdelre** [comment]
Hitesh could you please solve the menu icon?
it is huge and covers all writings....
please put it the way it was 
thankyou
